##***SIP LAB 2***

Krisha Chemburkar

I012

B1 Batch

Semester IV

BTech AI

### ***Aim:***

a. Obtain twiddle factor matrix

b. To find the DFT and IDFT of [1,2,2,1] using twiddle factor matrix.

c. To compute the DFT using matrix method and FFT function.

d. Observe and comment on execution time required for each of the above method.

In [3]:
import numpy as np

### ***Fast Fourier Transform and Inverse Fast Fourier Transform using direct functions***

In [4]:
x = np.array([1,2,2,1])

In [5]:
#DFT using FFT function
X = np.fft.fft(x)
X

array([ 6.+0.j, -1.-1.j,  0.+0.j, -1.+1.j])

In [8]:
#IDFT using IFFT function
x_est=np.fft.ifft(X)
x_est

array([1.+0.j, 2.+0.j, 2.+0.j, 1.+0.j])

### ***Fast Fourier Transform and Inverse Fast Fourier Transform using Twiddle Factor Matrix method***

In [6]:
#twiddle matrix for forward transform
N=4
w=np.zeros((4,4), dtype=complex)
for n in range(0,N):
  for k in range(0,N): 
    r,c = int(np.cos(2*np.pi*n*k/N)), -1*int(np.sin(2*np.pi*n*k/N))
    w[n][k]=complex(r,c)
print(w)

[[ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
 [ 1.+0.j  0.-1.j -1.+0.j  0.+1.j]
 [ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]
 [ 1.+0.j  0.+1.j -1.+0.j  0.-1.j]]


In [7]:
X1 = np.dot(w,np.transpose(x))
X1

array([ 6.+0.j, -1.-1.j,  0.+0.j, -1.+1.j])

In [9]:
#twiddle factor matrix for inverse transform
N=4
w_inv=np.zeros((4,4), dtype=complex)
for n in range(0,N):
  for k in range(0,N): 
    r,c = int(np.cos(2*np.pi*n*k/N)), int(np.sin(2*np.pi*n*k/N))
    w_inv[n][k]=complex(r,c)
print(w_inv)

[[ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
 [ 1.+0.j  0.+1.j -1.+0.j  0.-1.j]
 [ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]
 [ 1.+0.j  0.-1.j -1.+0.j  0.+1.j]]


In [10]:
x1 = (np.dot(w_inv,np.transpose(X1))/N)
x1

array([1.+0.j, 2.+0.j, 2.+0.j, 1.+0.j])

### ***Conclusion***
In this experiment we find the fast fourier transform and the inverse fast fourier transform using the direct functions and calculating it manually using formula. The execution time for both were almost equal. We understood the methods to compute fast fourier transform. 